//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class produtos
{
    public int idProduto { get; set; }
    public string nome { get; set; }
    public string nome_url { get; set; }
    public string descricao { get; set; }
    public string unidade { get; set; }
    public string codigoDeBarras { get; set; }
    public string referencia { get; set; }
    public Nullable<System.DateTime> dtCadastro { get; set; }
    public Nullable<bool> ativo { get; set; }

    public virtual tbprodutofotos tbprodutofotos { get; set; }
}

public partial class tbjuncaoprodutocategoria
{
    public int idJuncaoProdutoCategoria { get; set; }
    public Nullable<int> idProduto { get; set; }
    public Nullable<int> idProdutoCategoria { get; set; }
}

public partial class tbprodutofotos
{
    public int IdProdutoFoto { get; set; }
    public Nullable<int> IdProduto { get; set; }
    public string caminhoFoto { get; set; }

    public virtual produtos produtos { get; set; }
}

public partial class tbprodutoscategorias
{
    public int idProdutosCategorias { get; set; }
    public Nullable<int> idCategoriaPai { get; set; }
    public string nome { get; set; }
    public string nome_url { get; set; }
    public Nullable<bool> ativa { get; set; }
    public Nullable<int> ordem { get; set; }
}
